src/objects/Medication_Prescribed__c.object
<CustomObject>
    <fields>
        <fullName>Batch_Number__c</fullName>
        <label>Batch Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consultation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consultation</label>
        <referenceTo>Consultation__c</referenceTo>
        <relationshipLabel>Medication Prescribed</relationshipLabel>
        <relationshipName>Medication_Prescribed</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Medication_Name__c</fullName>
        <label>Medication Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Aciclovir 400mg (Box of 56)</fullName>
                </value>
                <value>
                    <fullName>Aciclovir 800mg (Box of 35)</fullName>
                </value>
                <value>
                    <fullName>Aciclovir Cream (Zovirax) 2g</fullName>
                </value>
                <value>
                    <fullName>Adrenaline 1mg /ml of 1 In 1000</fullName>
                </value>
                <value>
                    <fullName>Adrenaline Min-I-Jet 1 in 10,000 – 10 ml</fullName>
                </value>
                <value>
                    <fullName>Amiodarone Hydrochloride Min-I-Jet 30mg/ml</fullName>
                </value>
                <value>
                    <fullName>Amoxicillin Capsules 500mg (Box of 21)</fullName>
                </value>
                <value>
                    <fullName>Anthisan Cream 30g Tube</fullName>
                </value>
                <value>
                    <fullName>Anusol HC Ointment 30g tube</fullName>
                </value>
                <value>
                    <fullName>Atenolol 50 mg (Box of 28)</fullName>
                </value>
                <value>
                    <fullName>Atropine Sulphate Min-I-Jet 1 mg/10 ml – 10 ml</fullName>
                </value>
                <value>
                    <fullName>Azithromycin 500mg (Box of 3)</fullName>
                </value>
                <value>
                    <fullName>Bactroban Ointment (Mupirocin) 15g</fullName>
                </value>
                <value>
                    <fullName>Beclomethasone 100mcg MDI</fullName>
                </value>
                <value>
                    <fullName>Benoxinate Minims (Oxybuprocaine) 0.4% 1ml</fullName>
                </value>
                <value>
                    <fullName>Benzylpenicillin Vials 600mg (Box of 2)</fullName>
                </value>
                <value>
                    <fullName>Betamethasone (Betnovate Ointment) 30g</fullName>
                </value>
                <value>
                    <fullName>Bonjela Oral Gel 15g</fullName>
                </value>
                <value>
                    <fullName>Calamine Aqueous Cream BP 100g</fullName>
                </value>
                <value>
                    <fullName>Calcium Gluconate Gel and Injection 25g/10%</fullName>
                </value>
                <value>
                    <fullName>Cavit Boxes – 4 tubes</fullName>
                </value>
                <value>
                    <fullName>Ceftriaxone Vial (Rocephin)</fullName>
                </value>
                <value>
                    <fullName>Cetirizine Tablets 10 mg (Box of 30)</fullName>
                </value>
                <value>
                    <fullName>Cetrimide Cream BPC 30 g</fullName>
                </value>
                <value>
                    <fullName>Chloramphenicol 0.5% 10ml</fullName>
                </value>
                <value>
                    <fullName>Chloramphenicol 1% - 4g</fullName>
                </value>
                <value>
                    <fullName>Chlorhexidine 100ml</fullName>
                </value>
                <value>
                    <fullName>Chlorhexidine Gluconate Concentrate with Cetrimide - sachets (Tisept)</fullName>
                </value>
                <value>
                    <fullName>Chlorphenamine lnj 10mg/ml (Box of 5)</fullName>
                </value>
                <value>
                    <fullName>Chlorpromazine 25mg (Box of 28)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Medication Prescribed</label>
    <nameField>
        <displayFormat>MP - {000000}</displayFormat>
        <label>Medication Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medication Prescribed</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Site__c.object
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MedicationPrescriptionCtrl.cls
/**
 * Created by Adelchi on 14/04/2018.
 */

public with sharing class MedicationPrescriptionCtrl {

    public static Consultation__c consultation;
    public static Inventory__c iRecord;
    public static Medication_Prescribed__c medPrescribed;
    public static Site__c site;

   @AuraEnabled
    public static void getInventoryItem(String consultId, String InventoryName, String batchN, Integer qty){
       system.debug(InventoryName+'xxxxx'+consultId+'quantity>> '+qty);
       Boolean checkBatchNumber = ([SELECT count() FROM Inventory__c WHERE Batch_Number__c =: batchN]>0);
       if(!checkBatchNumber){
           throw new AuraHandledException('No Items are Available with this Batch Number!');
       }else{
           consultation = [SELECT Site__c FROM Consultation__c WHERE Id =: consultId LIMIT 1];
           for(Integer i=0; i<qty; i++){
               iRecord = [SELECT Id, Available__c, Removal_Reason__c, Batch_Number__c FROM Inventory__c WHERE SiteName__c =: consultation.Site__c AND Batch_Number__c =: batchN AND Name =: InventoryName AND Available__c = true LIMIT 1];
               system.debug(iRecord.Id);
               setInventoryItem(consultId);
           }
       }
    }

    @AuraEnabled
    public static void setInventoryItem(String conId){
        system.debug('inside set Inventory name method xxxxx   '+conId);
        iRecord.Available__c = false;
        iRecord.Removal_Reason__c = 'Used';
        iRecord.Consultation__c = conId;
        system.debug('inside set Inventory name method xxxxx   '+iRecord.Available__c);
        update iRecord;
    }

    @AuraEnabled
    public static List < String > getMedicationList(){
        system.debug('get medication list method started ');
        Medication_Prescribed__c mp = new Medication_Prescribed__c();
        List < String > medicationList = fetchPickList.getselectOptions(mp, 'Medication_Name__c');
        return medicationList;
    }

}